### ISSUE TITLE
Deploy Fractal subgraphs on Base Sepolia

### ISSUE THREAD

**Issue by adamgall** [decentdao/fractal-subgraph#9]
This issue is to track the work involved with deploying Fractal subgraphs for Base and Base Sepolia.

Related to:
- `interface`: https://github.com/decent-dao/fractal-interface/issues/1460
- `contracts`: https://github.com/decent-dao/fractal-contracts/issues/74

**Comment by Da-Colon** [comment]
Update: Currently Deploying to `Base Sepolia`.

Once testing has been completed, work will beging to deploy to `Base` mainnet

**Comment by adamgall** [comment]
This is completed, nice job @Da-Colon !
